name: Master-Merge
run-name: ${{github.actor}} pull requested to Master.
on:
  pull_request:
    branches:
      - master
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Test the Library
        run: mvn --batch-mode test
